### ISSUE TITLE
SocialLogin OAuthException: E_OAUTH_TOKEN_EXCHANGE: Oauth failed during redirect

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/adonis-mongodb-boilerplate#109]
Hi @duyluonglc , sorry for the trouble but i cannot manage to make the social login endpoint work.

I receive this error

```js
2018-04-13T02:08:31.056Z - error:  OAuthException: E_OAUTH_TOKEN_EXCHANGE: Oauth failed during redirect
    at Function.tokenExchangeException (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/ally/src/Exceptions/index.js:36:19)
    at Google.getUser (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/ally/src/Drivers/Google.js:196:31)
    at Authenticator.getUser (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/ally/src/Authenticator.js:103:45)
    at AuthController.socialLogin (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/app/Providers/NuviioProvider/Controllers/AuthController.js:136:73)
    at Server._routeHandler (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/framework/src/Server/index.js:121:31)
    at MiddlewareBase._resolveMiddleware (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/middleware-base/index.js:195:28)
    at Runnable._invoke (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/co-compose/src/Runnable.js:76:42)
    at once (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/co-compose/src/Runnable.js:73:34)
    at f (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/once/once.js:25:25)
    at ValidatorMiddleware.handle (/home/francisco/Repositories/Nuviio/Mercurio/server-v2/node_modules/@adonisjs/validator/src/Middleware/Validator.js:237:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

In my config/services.js file i have:

NOTE: This is a testing app so i really do not have a problem with sharing this keys.

```js
google: {
      clientId: Env.get('GOOGLE_CLIENT_ID'),
      clientSecret: Env.get('GOOGLE_CLIENT_SECRET'),
      redirectUri: `${Env.get('APP_URL')}`
    },
```

In my .env i have:

```js
GOOGLE_CLIENT_ID=558159843001-q142v75i3gv0bgffeep4ahpq7ahrcad9.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=3O0bUHlH60pqa31VDkpy3lK_
```

In my google app profile i have already created credentials for an oauth client with http://localhost:4000 as redirect url.

**Comment by duyluonglc** [comment]
Hi @franciscosucre 
check here
https://github.com/duyluonglc/adonis-ally/blob/316c7822f597eb8b73a4a7ee13c81d5989088e26/src/Drivers/Google.js#L194
did you send google token to `.getUser(googleTokenHere)`
