### ISSUE TITLE
Can't access /docs

### ISSUE THREAD

**Issue by TrippyHank** [duyluonglc/adonis-mongodb-boilerplate#12]
Tried to installed but got an error while accessing http://localhost:3333/docs
Am i missing something ?

```
$ node -v
v6.9.0
$  npm -v
5.2.0
```
Input
```
$ npm i && npm run dev
```

Output
```
> adonis-mongo-boilerplate@1.0.0 dev /Users/Hank/Projects/adonismongo
> nodemon --watch app --watch bootstrap --watch config --watch providers --watch .env -x node server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/Hank/Projects/adonismongo/app/**/* /Users/Hank/Projects/adonismongo/bootstrap/**/* /Users/Hank/Projects/adonismongo/config/**/* /Users/Hank/Projects/adonismongo/providers/**/* .env
[nodemon] starting `node server.js`
info adonis:framework +0ms serving app on localhost:3333
HttpException: Route not found /docs/localhost:3333/api-docs.json
    at Server._callRouteAction (/Users/Hank/Projects/adonismongo/node_modules/adonis-framework/src/Server/index.js:73:13)
    at finalHandler (/Users/Hank/Projects/adonismongo/node_modules/adonis-framework/src/Server/index.js:212:18)
    at next (native)
    at onFulfilled (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:65:19)
    at /Users/Hank/Projects/adonismongo/node_modules/co/index.js:54:5
    at co (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:50:10)
    at toPromise (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:118:63)
    at next (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:69:7)
    at /Users/Hank/Projects/adonismongo/node_modules/co/index.js:54:5
    at co (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:50:10)
    at toPromise (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:118:63)
    at next (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/Hank/Projects/adonismongo/node_modules/co/index.js:69:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

## http://localhost:3333/docs

![capture d ecran 2017-07-11 a 20 36 04](https://user-images.githubusercontent.com/9848190/28096675-a5ffa88a-6678-11e7-862c-804eb77ac259.png)

**Comment by duyluonglc** [comment]
@TrippyHank did you forget step 4?
https://github.com/duyluonglc/adonis-mongodb-boilerplate#arrow_up-how-to-setup
after copy .env file you need to set the BASE_URL variable as
BASE_URL=http://localhost:3333

**Comment by TrippyHank** [comment]
@duyluonglc I was about to reply on this, feel dumb on this one 🤦‍♂️ 
I did copied the .env.example and filled most of the requirements but i had :
BASE_URL=localhost:3333

Once modified with protocol, works like a charm !

![capture d ecran 2017-07-12 a 16 16 29](https://user-images.githubusercontent.com/9848190/28138079-82e1fe20-671d-11e7-9877-b3336a9df303.png)

Thanks !
